"""empty message

Revision ID: 0135f79d5633
Revises: 4900f23069dd
Create Date: 2025-05-03 14:41:33.047556

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0135f79d5633'
down_revision = '4900f23069dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_media_dataset', schema=None) as batch_op:
        batch_op.alter_column('target',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_media_dataset', schema=None) as batch_op:
        batch_op.alter_column('target',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###
