"""增加角色权限：数据集和模型参数限额

Revision ID: 042b72bd074d
Revises: 6524fecc783c
Create Date: 2025-04-05 19:54:50.685759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '042b72bd074d'
down_revision = '6524fecc783c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_dataset_uploads', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_model_param_size', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('max_model_param_size')
        batch_op.drop_column('max_dataset_uploads')

    # ### end Alembic commands ###
