"""empty message

Revision ID: 0c13819a2f5c
Revises: 79acb27f9b46
Create Date: 2025-05-07 11:06:42.833784

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0c13819a2f5c'
down_revision = '79acb27f9b46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relations',
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('source_id', 'target_id', name=op.f('pk_relations'))
    )
    op.create_table('weibo_users',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('birthday', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('verified_reason', sa.String(length=128), nullable=True),
    sa.Column('talent', sa.String(length=64), nullable=True),
    sa.Column('education', sa.String(length=128), nullable=True),
    sa.Column('work', sa.String(length=128), nullable=True),
    sa.Column('weibo_num', sa.Integer(), nullable=True),
    sa.Column('following', sa.Integer(), nullable=True),
    sa.Column('followers', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('last_crawled', sa.DateTime(), nullable=True, comment='最近一次爬取用户信息时间'),
    sa.Column('graph_layout', sa.JSON(), nullable=True, comment='关系图预计算布局结果'),
    sa.Column('graph_computed_at', sa.DateTime(), nullable=True, comment='关系图计算时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weibo_users'))
    )
    op.create_table('weibo_posts',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('article_url', sa.String(length=255), nullable=False),
    sa.Column('original_pictures', sa.JSON(), nullable=False),
    sa.Column('retweet_pictures', sa.JSON(), nullable=True),
    sa.Column('original_id', sa.String(length=255), nullable=True),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.Column('publish_place', sa.String(length=128), nullable=True),
    sa.Column('publish_time', sa.DateTime(), nullable=False),
    sa.Column('publish_tool', sa.String(length=64), nullable=True),
    sa.Column('up_num', sa.Integer(), nullable=True),
    sa.Column('retweet_num', sa.Integer(), nullable=True),
    sa.Column('comment_num', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['weibo_users.id'], name=op.f('fk_weibo_posts_user_id_weibo_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weibo_posts'))
    )
    with op.batch_alter_table('weibo_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weibo_posts_user_id'), ['user_id'], unique=False)

    op.create_table('weibo_user_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('data_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['data_id'], ['weibo_users.id'], name=op.f('fk_weibo_user_images_data_id_weibo_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weibo_user_images'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weibo_user_images')
    with op.batch_alter_table('weibo_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weibo_posts_user_id'))

    op.drop_table('weibo_posts')
    op.drop_table('weibo_users')
    op.drop_table('relations')
    # ### end Alembic commands ###
