"""调整多模态数据集结构

Revision ID: 2296e3d7a585
Revises: c6e46c0016c0
Create Date: 2025-04-21 14:54:59.365318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2296e3d7a585'
down_revision = 'c6e46c0016c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_index('uq_images_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.create_index('uq_images_path', ['path'], unique=True)

    # ### end Alembic commands ###
