"""增加多模态数据集

Revision ID: 32261cf03c38
Revises: 98c322fd694c
Create Date: 2025-04-21 11:22:09.069838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32261cf03c38'
down_revision = '98c322fd694c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('multimodal_image_dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('processed_input', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('label_rumor', sa.SmallInteger(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('split', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_multimodal_image_dataset_dataset_id_datasets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_multimodal_image_dataset'))
    )
    with op.batch_alter_table('multimodal_image_dataset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_multimodal_image_dataset_dataset_id'), ['dataset_id'], unique=False)

    with op.batch_alter_table('social_media_dataset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_media_dataset', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('multimodal_image_dataset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_multimodal_image_dataset_dataset_id'))

    op.drop_table('multimodal_image_dataset')
    # ### end Alembic commands ###
