"""修改字段大小

Revision ID: 478db91b4712
Revises: 32261cf03c38
Create Date: 2025-04-21 14:17:44.951716

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '478db91b4712'
down_revision = '32261cf03c38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('multimodal_image_dataset', schema=None) as batch_op:
        batch_op.alter_column('image_path',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('multimodal_image_dataset', schema=None) as batch_op:
        batch_op.alter_column('image_path',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
