"""empty message

Revision ID: 47e95e0bb9fa
Revises: 0135f79d5633
Create Date: 2025-05-04 15:39:49.325748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47e95e0bb9fa'
down_revision = '0135f79d5633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weibo_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_crawled', sa.DateTime(), nullable=True, comment='最近一次爬取用户信息时间'))
        batch_op.add_column(sa.Column('graph_layout', sa.JSON(), nullable=True, comment='关系图预计算布局结果'))
        batch_op.add_column(sa.Column('graph_computed_at', sa.DateTime(), nullable=True, comment='关系图计算时间'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weibo_users', schema=None) as batch_op:
        batch_op.drop_column('graph_computed_at')
        batch_op.drop_column('graph_layout')
        batch_op.drop_column('last_crawled')

    # ### end Alembic commands ###
