"""empty message

Revision ID: 4900f23069dd
Revises: f4a3cb55fde3
Create Date: 2025-05-03 14:39:15.219629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4900f23069dd'
down_revision = 'f4a3cb55fde3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_media_dataset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_media_dataset', schema=None) as batch_op:
        batch_op.drop_column('target')

    # ### end Alembic commands ###
