"""初始化migrate

Revision ID: 4ef829940a41
Revises: 330ad2ca3fc7
Create Date: 2025-04-02 19:00:21.415279

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ef829940a41'
down_revision = '330ad2ca3fc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_checkpoints', schema=None) as batch_op:
        batch_op.drop_column('shared')
        batch_op.drop_column('default')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_checkpoints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('shared', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
