"""初始化migrate

Revision ID: 5c2d01cda200
Revises: 4ef829940a41
Create Date: 2025-04-02 19:00:42.067803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c2d01cda200'
down_revision = '4ef829940a41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_checkpoints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('shared', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_checkpoints', schema=None) as batch_op:
        batch_op.drop_column('shared')
        batch_op.drop_column('default')

    # ### end Alembic commands ###
