"""增加模型大小字段

Revision ID: 5d4955fd97b1
Revises: 042b72bd074d
Create Date: 2025-04-06 14:15:27.855008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d4955fd97b1'
down_revision = '042b72bd074d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_checkpoints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_checkpoints', schema=None) as batch_op:
        batch_op.drop_column('size')

    # ### end Alembic commands ###
