"""增加数据集字段

Revision ID: 6524fecc783c
Revises: c9f89755304a
Create Date: 2025-04-05 19:06:49.921991

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6524fecc783c'
down_revision = 'c9f89755304a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_time', sa.DateTime(), nullable=True))
        batch_op.drop_column('update_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_time', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('updated_time')

    # ### end Alembic commands ###
