"""初始化migrate

Revision ID: 6e5f6c660d70
Revises: 5c2d01cda200
Create Date: 2025-04-02 19:04:33.742471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e5f6c660d70'
down_revision = '5c2d01cda200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_instance', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_column('model_instance')

    # ### end Alembic commands ###
