"""增加字段标识模型超参数

Revision ID: 78ac5133712f
Revises: cb2c6a81d32b
Create Date: 2025-04-06 22:09:09.220090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78ac5133712f'
down_revision = 'cb2c6a81d32b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_checkpoints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('complete', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_checkpoints', schema=None) as batch_op:
        batch_op.drop_column('complete')

    # ### end Alembic commands ###
