"""empty message

Revision ID: 79acb27f9b46
Revises: 47e95e0bb9fa
Create Date: 2025-05-04 21:32:44.396687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '79acb27f9b46'
down_revision = '47e95e0bb9fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relations',
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('source_id', 'target_id', name=op.f('pk_relations'))
    )
    op.create_table('weibo_users',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('birthday', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('verified_reason', sa.String(length=128), nullable=True),
    sa.Column('talent', sa.String(length=64), nullable=True),
    sa.Column('education', sa.String(length=128), nullable=True),
    sa.Column('work', sa.String(length=128), nullable=True),
    sa.Column('weibo_num', sa.Integer(), nullable=True),
    sa.Column('following', sa.Integer(), nullable=True),
    sa.Column('followers', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('avatar_url', sa.String(length=256), nullable=True),
    sa.Column('last_crawled', sa.DateTime(), nullable=True, comment='最近一次爬取用户信息时间'),
    sa.Column('graph_layout', sa.JSON(), nullable=True, comment='关系图预计算布局结果'),
    sa.Column('graph_computed_at', sa.DateTime(), nullable=True, comment='关系图计算时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weibo_users'))
    )
    op.create_table('weibo_user_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('data_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['data_id'], ['weibo_users.id'], name=op.f('fk_weibo_user_images_data_id_weibo_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weibo_user_images'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weibo_user_images')
    op.drop_table('weibo_users')
    op.drop_table('relations')
    # ### end Alembic commands ###
