"""重构数据集存储表

Revision ID: 85d7e8ac0206
Revises: a2e5e503c070
Create Date: 2025-04-13 19:15:57.284719

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '85d7e8ac0206'
down_revision = 'a2e5e503c070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_media_dataset',
    sa.Column('key_word', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=64), nullable=True),
    sa.Column('publish_time', sa.DateTime(), nullable=True),
    sa.Column('label', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('news_source', sa.String(length=64), nullable=True),
    sa.Column('source_station', sa.String(length=64), nullable=True),
    sa.Column('count_comments', sa.Integer(), nullable=True),
    sa.Column('count_likes', sa.Integer(), nullable=True),
    sa.Column('count_forward', sa.Integer(), nullable=True),
    sa.Column('count_favorites', sa.Integer(), nullable=True),
    sa.Column('detail_address', sa.String(length=128), nullable=True),
    sa.Column('count_follwers', sa.Integer(), nullable=True),
    sa.Column('count_blogs', sa.Integer(), nullable=True),
    sa.Column('auth_type', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_social_media_dataset_dataset_id_datasets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_media_dataset'))
    )
    with op.batch_alter_table('social_media_dataset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_social_media_dataset_dataset_id'), ['dataset_id'], unique=False)

    op.drop_table('emotion_dataset')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emotion_dataset',
    sa.Column('key_word', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('text', mysql.TEXT(), nullable=True),
    sa.Column('author', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('publish_time', mysql.DATETIME(), nullable=True),
    sa.Column('label', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('location', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('news_source', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('source_station', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('count_comments', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('count_likes', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('count_forward', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('count_favorites', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('detail_address', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('count_follwers', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('count_blogs', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('auth_type', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name='fk_emotion_dataset_dataset_id_datasets'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('social_media_dataset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_social_media_dataset_dataset_id'))

    op.drop_table('social_media_dataset')
    # ### end Alembic commands ###
