"""增加模型属性：是否可训练

Revision ID: 98c322fd694c
Revises: d9b74e1c953a
Create Date: 2025-04-14 15:21:53.643347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98c322fd694c'
down_revision = 'd9b74e1c953a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trainable', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_column('trainable')

    # ### end Alembic commands ###
