"""增加字段标识模型超参数

Revision ID: a2e5e503c070
Revises: 78ac5133712f
Create Date: 2025-04-06 22:15:11.097099

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a2e5e503c070'
down_revision = '78ac5133712f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_checkpoints', schema=None) as batch_op:
        batch_op.alter_column('checkpoint_path',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
        batch_op.alter_column('version',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_checkpoints', schema=None) as batch_op:
        batch_op.alter_column('version',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('checkpoint_path',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)

    # ### end Alembic commands ###
