"""调整多模态数据集结构

Revision ID: c6e46c0016c0
Revises: 478db91b4712
Create Date: 2025-04-21 14:51:08.133664

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c6e46c0016c0'
down_revision = '478db91b4712'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('data_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['data_id'], ['multimodal_image_dataset.id'], name=op.f('fk_images_data_id_multimodal_image_dataset')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_images')),
    sa.UniqueConstraint('path', name=op.f('uq_images_path'))
    )
    with op.batch_alter_table('multimodal_image_dataset', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('multimodal_image_dataset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', mysql.VARCHAR(length=512), nullable=True))

    op.drop_table('images')
    # ### end Alembic commands ###
