"""增加字段标识模型超参数

Revision ID: cb2c6a81d32b
Revises: 5d4955fd97b1
Create Date: 2025-04-06 20:54:39.312508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb2c6a81d32b'
down_revision = '5d4955fd97b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_checkpoints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hyperparameters', sa.JSON(), nullable=True))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('tag')

    with op.batch_alter_table('model_checkpoints', schema=None) as batch_op:
        batch_op.drop_column('hyperparameters')

    # ### end Alembic commands ###
