"""重构数据集存储表

Revision ID: d9b74e1c953a
Revises: 85d7e8ac0206
Create Date: 2025-04-14 10:49:31.413140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd9b74e1c953a'
down_revision = '85d7e8ac0206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valid_fields', sa.JSON(), nullable=True))

    with op.batch_alter_table('social_media_dataset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('split', sa.String(length=32), nullable=True))
        batch_op.alter_column('text',
               existing_type=mysql.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_media_dataset', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.drop_column('split')

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_column('valid_fields')

    # ### end Alembic commands ###
