"""empty message

Revision ID: ef9456a89ff2
Revises: 0c13819a2f5c
Create Date: 2025-05-12 11:56:04.297236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef9456a89ff2'
down_revision = '0c13819a2f5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialog_sessions',
    sa.Column('session_code', sa.String(length=64), nullable=False),
    sa.Column('utterance_ids', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('split', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_dialog_sessions_dataset_id_datasets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dialog_sessions'))
    )
    with op.batch_alter_table('dialog_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dialog_sessions_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dialog_sessions_session_code'), ['session_code'], unique=True)

    op.create_table('dialog_utterances',
    sa.Column('utterance_code', sa.String(length=64), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('speaker', sa.String(length=32), nullable=True),
    sa.Column('emotion', sa.String(length=32), nullable=True),
    sa.Column('session_code', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('split', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_dialog_utterances_dataset_id_datasets')),
    sa.ForeignKeyConstraint(['session_code'], ['dialog_sessions.session_code'], name=op.f('fk_dialog_utterances_session_code_dialog_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dialog_utterances'))
    )
    with op.batch_alter_table('dialog_utterances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dialog_utterances_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dialog_utterances_session_code'), ['session_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_dialog_utterances_utterance_code'), ['utterance_code'], unique=True)

    op.create_table('pa_account',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('last_crawled', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pa_account'))
    )
    op.create_table('pa_article',
    sa.Column('fakeid', sa.String(length=255), nullable=False),
    sa.Column('article_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fakeid'], ['pa_account.id'], name=op.f('fk_pa_article_fakeid_pa_account')),
    sa.PrimaryKeyConstraint('article_id', name=op.f('pk_pa_article'))
    )
    op.create_table('pa_article_content',
    sa.Column('article_id', sa.String(length=255), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=True, comment='gzip 压缩后的全文 HTML'),
    sa.ForeignKeyConstraint(['article_id'], ['pa_article.article_id'], name=op.f('fk_pa_article_content_article_id_pa_article')),
    sa.PrimaryKeyConstraint('article_id', name=op.f('pk_pa_article_content'))
    )
    with op.batch_alter_table('weibo_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_crawled_wblogs', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_visible', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weibo_users', schema=None) as batch_op:
        batch_op.drop_column('is_visible')
        batch_op.drop_column('last_crawled_wblogs')

    op.drop_table('pa_article_content')
    op.drop_table('pa_article')
    op.drop_table('pa_account')
    with op.batch_alter_table('dialog_utterances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dialog_utterances_utterance_code'))
        batch_op.drop_index(batch_op.f('ix_dialog_utterances_session_code'))
        batch_op.drop_index(batch_op.f('ix_dialog_utterances_dataset_id'))

    op.drop_table('dialog_utterances')
    with op.batch_alter_table('dialog_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dialog_sessions_session_code'))
        batch_op.drop_index(batch_op.f('ix_dialog_sessions_dataset_id'))

    op.drop_table('dialog_sessions')
    # ### end Alembic commands ###
