"""empty message

Revision ID: f4a3cb55fde3
Revises: 2296e3d7a585
Create Date: 2025-05-01 09:29:29.395042

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f4a3cb55fde3'
down_revision = '2296e3d7a585'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relations',
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('source_id', 'target_id', name=op.f('pk_relations'))
    )
    op.create_table('weibo_users',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('birthday', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('verified_reason', sa.String(length=128), nullable=True),
    sa.Column('talent', sa.String(length=64), nullable=True),
    sa.Column('education', sa.String(length=128), nullable=True),
    sa.Column('work', sa.String(length=128), nullable=True),
    sa.Column('weibo_num', sa.Integer(), nullable=True),
    sa.Column('following', sa.Integer(), nullable=True),
    sa.Column('followers', mysql.BIGINT(unsigned=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weibo_users'))
    )
    with op.batch_alter_table('application_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_type', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_group', schema=None) as batch_op:
        batch_op.drop_column('task_type')

    op.drop_table('weibo_users')
    op.drop_table('relations')
    # ### end Alembic commands ###
