# 构建阶段：使用 Node 镜像构建 Vite 项目
FROM docker.1ms.run/node:20.19 AS builder

# 设置工作目录
WORKDIR /usr/src/app

# 先复制依赖定义文件，利用缓存层
COPY ./frontend/package*.json ./

# 安装项目依赖
RUN npm install

# 复制整个前端代码
COPY ./frontend ./

# 重新构建项目（例如生成 dist 目录）
RUN npm run build

# 运行阶段：使用 Nginx 镜像作为运行时镜像
FROM docker.1ms.run/nginx:latest

# 将构建阶段生成的 dist 目录复制到 Nginx 的默认静态文件目录
COPY --from=builder /usr/src/app/dist /usr/share/nginx/html

# 复制自定义的 Nginx 配置文件到 Nginx 容器内
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

# 暴露容器内端口
EXPOSE 80
